#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NetError {
    NetworkDown,
    NotConfigured,
    NotReady,
    NotFound,
    InvalidAddress,
    InvalidPort,
    InvalidArgument,
    InvalidSocket,
    InvalidRequest,
    InvalidBuffer,
    NoSocketAvailable,
    NoRequestAvailable,
    NoBufferAvailable,
    ConnectionRefused,
    ConnectionReset,
    ConnectionAborted,
    AlreadyConnected,
    NotConnected,
    TimedOut,
    WouldBlock,
    Busy,
    Closed,
    DnsQueryFailed,
    IcmpBindFailed,
    IcmpSendFailed,
    QueueFull,
    Internal,
}

pub type NetResult<T> = core::result::Result<T, NetError>;
